/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110196-g639ded10e3-20230409"
#endif /* AVUTIL_FFVERSION_H */
